### ISSUE TITLE
Parser: ndla.no

### ISSUE THREAD

**Issue by ghveem** [michaelmcmillan/LittList#80]
Innspelt til forbetring av resultat frå http://ndla.no/ på littlist.no: 
døme: url: http://ndla.no/nb/node/53722?fag=7
- har forfattar i <div class="owner rs_skip»> (det kan vere fleire)
- publisert / oppdatert: <div id="edit-dates" class="rs_skip">

Obs: 
rs_skip fortel at readspeaker (http://www.readspeaker.com/nb/) ikkje skal lesa opp tekst. 
publiseringsdato er ikkje synleg om ikkje ?fag= er med i url. (bruk gjerne ?fag=7 (naturfag) uansett kva url ein prøver å slå opp. Døme:
unik sideID: 2745
variantar: 
nb: 
http://ndla.no/nb/node/2745?fag=36
http://ndla.no/nb/node/2745

nn: 
http://ndla.no/nn/node/24606?fag=36
http://ndla.no/nn/node/24606

**Comment by michaelmcmillan** [comment]
Takk for forslaget @ghveem!

Som du kanskje ser i koden blir alle fritekst-søk blir kjørt mot Bibsys [FunnelController.js:38-45](https://github.com/michaelmcmillan/LittList/blob/62c95f137de9e2a7e37d0bbbac6d7a66018ca482/controllers/query/funnel.js#L38-L45). Det vil være en del jobb å hente data fra to forskjellige databaser samtidig (NDLA og Bibsys) når noen søker på forfatter, tittel eller ISBN. Men med det sagt kunne det kanskje vært nyttig å implementere NDLA-parseren slik at dersom en NDLA.no lenke ble søkt på hentet LittList ut metadataen til ressursen (slik du foreslår over). 

Kunne dette vært aktuelt, eller tenkte du hovedsaklig å tilby NDLA resultater på lik linje med Bibsys? Eventuelt kunne man hatt en checkbox som brukere kun huke av på når det kommer til valg av hvilken bokdatabase de ønsker å søke i. 

Ser fram til å høre hva du tenker :smile:

**Comment by ghveem** [comment]
Ah, eg tenkte ikkje på å implementera søket (søk frå littlist med oppslag på NDLA), eg testa bare å lima inn lenkene: http://ndla.no/nb/node/53722?fag=7 på littlist. 
Då vert det slik: 
Litteraturliste
Anon, Eksamensordning i naturfag for elever og privatister. Available at: http://ndla.no/nb/node/53722?fag=7 [Åpnet 2015–5a].

Søk vert nok veldig omfattande, men tenkte at data kunne bli med om ein limer inn url. 
Kanskje lettare å hente i metadata?

_link rel="canonical" href="http://ndla.no/nb/node/53722"/_
_meta name="fagkode" content="7"/_ (altså ?fag=7 i url for å sjå datoar)

**Comment by michaelmcmillan** [comment]
Dette er nå implementert. Flott om du gidder å teste det ut :+1: Det er nok noen tilfeller jeg ikke har tenkt på hvor den vil gjøre feil - vi får se :bug: 

Når du tester må du huske på å ikke bruke gamle url'er du har tastet inn. LittList cacher nemlig alt.

**Comment by ghveem** [comment]
Har testa og det ser bra ut med alle stilar! Takk!
Røyert, H., 2014. Eksamensstoff på ndla. Available at: http://ndla.no/nb/node/133021?fag=36 [Åpnet 2015–5].

Røyert, H. & Nyborg, J.N., 2014. Hjelp til eksamen. Available at: http://ndla.no/nb/node/132866?fag=135085 [Åpnet 2015–5].
